'use client';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/atoms/Button';
import { SectionHeading } from '@/components/atoms/SectionHeading';
import { SearchPanel } from '@/components/molecules/SearchPanel';
import { PropertyCard } from '@/components/molecules/PropertyCard';
import { Header } from '@/components/organisms/Header';
import { PropertyModal } from '@/components/organisms/PropertyModal';
import { copy, Locale } from '@/lib/i18n';
import { Property } from '@/lib/types';

const services = [['⌂','Property Buying','Find your dream home with expert guidance through every step of the buying process.'],['$','Property Selling','Maximize your property value with our comprehensive selling process and market expertise.'],['↗','Real Estate Investment','Build wealth through strategic real estate investments with professional portfolio management.']];
const agents = [['Malak Khraisat','Riyadh','18+'],['Ahmed Al-Rashid','KAFD & Diplomatic Quarter','20+'],['Sarah Johnson','Corniche & Al Hamra','14+'],['Fatima Al-Zahra','Al Olaya','15+']];

export default function Home() {
 const [locale,setLocale] = useState<Locale>('en'); const t = copy[locale];
 const [properties,setProperties] = useState<Property[]>([]); const [selected,setSelected] = useState<Property | null>(null); const [query,setQuery] = useState(''); const [roi,setRoi] = useState(2.4); const [activeTab,setActiveTab] = useState<'buy' | 'sell' | 'invest'>('buy'); const [showSignIn,setShowSignIn] = useState(false); const [propertyType,setPropertyType] = useState('All'); const [priceOrder,setPriceOrder] = useState<'low' | 'high'>('low'); const [showAll,setShowAll] = useState(false); const [contactTopic,setContactTopic] = useState('Buy Property');
 useEffect(() => { fetch('/api/properties').then(r => r.json()).then(setProperties); fetch('/api/market').then(r => r.json()).then(d => setRoi(d.roi)); }, []);
 const displayed = useMemo(() => properties.filter(p => (propertyType === 'All' || p.type === propertyType) && (p.title.toLowerCase().includes(query.toLowerCase()) || p.location.toLowerCase().includes(query.toLowerCase()) || p.type.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => priceOrder === 'low' ? a.price - b.price : b.price - a.price),[properties,query,propertyType,priceOrder]);
 const rtl = locale === 'ar';
 const openContact = (topic: string) => { setContactTopic(topic); document.querySelector('main form')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
 return <main dir={rtl ? 'rtl' : 'ltr'} className="overflow-hidden bg-white">
  <div className="relative min-h-[560px] bg-slate-900 bg-[linear-gradient(rgba(9,30,43,.52),rgba(9,30,43,.52)),url('https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=2000&q=85')] bg-cover bg-center">
   <Header labels={t} onLanguage={() => setLocale(rtl ? 'en' : 'ar')} onSignIn={() => setShowSignIn(true)} onGetStarted={() => document.querySelector('main form')?.scrollIntoView({ behavior: 'smooth', block: 'center' })} />
   <div className="mx-auto flex min-h-[560px] max-w-4xl flex-col items-center justify-center px-5 pt-20 text-center text-white"><h1 className="max-w-3xl text-4xl font-bold leading-tight md:text-6xl">{t.hero}<br/><span className="text-sand">{t.accent}</span></h1><p className="mt-5 max-w-2xl leading-6">{t.heroText}</p><SearchPanel search={setQuery} activeTab={activeTab} setActiveTab={setActiveTab} labels={t}/><p className="mt-3 text-sm font-bold text-sand">{activeTab === 'buy' ? 'Browse premium properties for sale' : activeTab === 'sell' ? 'Request a valuation and sell with confidence' : 'Explore property investment opportunities'}</p><div className="mt-6 grid w-full max-w-xl grid-cols-3 border-t border-white/30 pt-4 text-center"><b>2,500+<small className="mt-1 block font-normal">Premium Properties</small></b><b>150+<small className="mt-1 block font-normal">Expert Agents</small></b><b>98%<small className="mt-1 block font-normal">Client Satisfaction</small></b></div></div>
  </div>
  <section id="buy" className="section bg-slate-50"><SectionHeading title={t.featured} text={t.featuredText}/><div className="mb-6 flex flex-wrap gap-2">{[['All',t.all],['Apartment','Apartment'],['Villa','Villa'],['Penthouse','Penthouse'],['Townhouse','Townhouse'],['Loft','Loft'],['Compound','Compound']].map(([type,label])=><button type="button" key={type} onClick={() => { setPropertyType(type); setShowAll(false); }} className={`pill font-bold transition ${propertyType === type ? 'bg-navy text-white' : 'bg-white text-ink hover:border-navy'}`}>{label}</button>)}<select aria-label="Sort properties by price" value={priceOrder} onChange={e => setPriceOrder(e.target.value as 'low' | 'high')} className="ml-auto rounded border border-slate-200 bg-white px-3 py-1 text-xs"><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option></select></div>{displayed.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{displayed.slice(0, showAll ? displayed.length : 3).map(p=><PropertyCard key={p.id} property={p} onSelect={()=>setSelected(p)} onContact={() => openContact(`Enquiry: ${p.title}`)} labels={t}/>)}</div> : <p className="rounded-xl bg-white p-8 text-center text-slate-500">No properties match this filter.</p>}{displayed.length > 3 && <div className="mt-8 text-center"><button type="button" onClick={() => setShowAll(value => !value)} className="rounded border border-navy px-5 py-3 text-sm font-bold text-navy">{showAll ? 'Show Fewer Properties' : 'View All Properties'} ↗</button></div>}</section>
  <section id="sell" className="section"><SectionHeading title={t.services} text="Comprehensive real estate solutions tailored to your needs"/><div className="grid gap-5 md:grid-cols-3">{services.map(([icon,title,description])=><article key={title} className="rounded-xl bg-slate-50 p-7"><span className="grid h-11 w-11 place-items-center rounded-lg bg-navy text-xl text-white">{icon}</span><h3 className="mt-5 font-bold">{title}</h3><p className="my-4 text-sm leading-6 text-slate-600">{description}</p><ul className="mb-5 space-y-2 text-sm text-green-600"><li>◉ Property Search</li><li>◉ Market Analysis</li><li>◉ Legal Assistance</li></ul><Button onClick={() => openContact(title)} className="w-full">Explore Services ↗</Button></article>)}</div></section>
  <section id="invest" className="section bg-slate-50"><SectionHeading title={t.tools} text="Calculate your returns and make informed investment decisions"/><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl bg-white p-6 shadow-card"><h3 className="font-bold">▣ ROI Calculator</h3>{[['Property Value','1600000'],['Monthly Rent','8000'],['Loan Amount','1000000'],['Interest Rate (%)','3.5']].map(([a,b])=><label key={a} className="mt-4 block text-xs font-semibold">{a}<input defaultValue={b} className="mt-1 w-full rounded bg-slate-100 p-2 font-normal"/></label>)}<select className="mt-4 w-full rounded bg-slate-100 p-2 text-sm"><option>25 years</option></select></div><div className="space-y-4"><div className="rounded-xl bg-white p-6 shadow-card"><h3 className="font-bold">Investment Summary</h3><p className="mt-5 flex justify-between border-b py-3 text-sm">Monthly Payment <b>$5,006</b></p><p className="flex justify-between py-3 text-sm">Annual Rent <b>$96,000</b></p><div className="rounded bg-navy p-3 text-center font-bold text-white">ROI &nbsp; {roi.toFixed(2)}%</div></div><div className="rounded-xl bg-white p-6 shadow-card"><h3 className="font-bold">Market Insights</h3><p className="mt-4 text-sm text-green-600">● Property values increased 8.7% this year.</p><p className="mt-3 text-sm">◧ Average rental yield: 6.5%</p></div><Button onClick={() => openContact('Investment Consultation')} className="w-full">Get Investment Consultation ↗</Button></div></div></section>
  <section id="agents" className="section"><SectionHeading title={t.agentsTitle} text="Work with Saudi Arabia’s top-rated real estate professionals"/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{agents.map(([name,place,sales],i)=><article key={name} className="rounded-xl bg-white p-5 text-center shadow-card"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-sand text-2xl">{['👨🏻','👩🏻','👨🏽','👩🏼'][i]}</div><h3 className="mt-4 font-bold">{name}</h3><p className="text-xs text-slate-500">{place}</p><div className="my-4 flex justify-between text-xs"><span>Sales:</span><b>{sales}</b></div><Button onClick={() => openContact(`Contact ${name}`)} className="w-full">✉ {t.contact}</Button><button type="button" onClick={() => { window.location.href = 'tel:+966111234567'; }} className="mt-2 w-full rounded border py-2 text-xs">⌕ Call</button></article>)}</div></section>
  <section id="transactions" className="section bg-white"><SectionHeading title="Recent Transactions" text="A transparent view of recent premium property activity"/><div className="overflow-hidden rounded-xl border border-slate-200"><div className="grid grid-cols-3 bg-slate-50 p-4 text-sm font-bold"><span>Property</span><span>Location</span><span>Sale Price</span></div>{properties.slice(0,3).map(p => <div key={p.id} className="grid grid-cols-3 border-t p-4 text-sm"><span>{p.title}</span><span>{p.location}</span><b className="text-navy">${p.price.toLocaleString()}</b></div>)}</div></section>
  <section id="indices" className="section bg-slate-50"><SectionHeading title={t.insights} text="Stay informed with the latest real estate trends and market analysis"/><div className="grid gap-5 md:grid-cols-3">{['Riyadh Real Estate Market Report Q4 2024','Investment Opportunities in Jeddah Waterfront','Vision 2030 Impact on Real Estate'].map((x,i)=><article key={x} className="rounded-xl bg-white p-5 shadow-card"><span className="pill">{i===0?'Market Report':'Investment Guide'}</span><b className="float-right text-green-600">+{8-i}.2%</b><h3 className="mt-5 font-bold">{x}</h3><p className="my-4 text-sm text-slate-600">Property values continue to grow in key economic zones and cities.</p><a className="text-sm font-bold text-navy">Read More ↗</a></article>)}</div></section>
  <section className="section bg-navy text-white"><div className="grid items-center gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">{t.ready}</h2><p className="mt-4 max-w-md leading-7">Connect with our experts today and take the first step towards your real estate goals.</p><div className="mt-7 space-y-3 text-sm"><p>☎ Call Us<br/><b>+966 11 123 4567</b></p><p>✉ Email Us<br/><b>info@premiumrealestate.sa</b></p><p>⌖ Visit Us<br/><b>King Fahd Road, Riyadh</b></p></div></div><form className="rounded-xl bg-white p-6 text-ink"><h3 className="font-bold">Send us a message</h3><input placeholder="Full Name" className="mt-4 w-full rounded bg-slate-100 p-3 text-sm"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><input placeholder="Email" className="rounded bg-slate-100 p-3 text-sm"/><input placeholder="Phone" className="rounded bg-slate-100 p-3 text-sm"/></div><select value={contactTopic} onChange={e => setContactTopic(e.target.value)} className="mt-3 w-full rounded bg-slate-100 p-3 text-sm"><option>Buy Property</option><option>Property Buying</option><option>Property Selling</option><option>Real Estate Investment</option><option>Investment Consultation</option>{contactTopic.startsWith('Contact ') || contactTopic.startsWith('Enquiry: ') ? <option>{contactTopic}</option> : null}</select><textarea placeholder="Tell us about your requirements..." className="mt-3 h-28 w-full rounded bg-slate-100 p-3 text-sm"/><Button className="mt-3 w-full">Send Message ↗</Button></form></div></section>
  <footer className="bg-[#101828] px-5 py-12 text-sm text-slate-300 md:px-10 lg:px-[7%]"><div className="grid gap-8 md:grid-cols-4"><p>Saudi Arabia’s premium real estate platform for buyers, sellers, and investors.</p><p><b className="text-white">Services</b><br/>Buy Property<br/>Sell Property<br/>Investment</p><p><b className="text-white">Locations</b><br/>Riyadh<br/>Jeddah<br/>Dammam<br/>Mecca</p><p><b className="text-white">Contact</b><br/>+966 11 123 4567<br/>info@premiumrealestate.sa</p></div><p className="mt-10 border-t border-slate-700 pt-5 text-xs">© 2024 Premium Real Estate. All rights reserved.</p></footer>
  {selected && <PropertyModal property={selected} close={()=>setSelected(null)} labels={t}/>} 
  {showSignIn && <div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/60 p-5"><form className="relative w-full max-w-sm rounded-xl bg-white p-6 text-ink shadow-2xl"><button type="button" onClick={() => setShowSignIn(false)} className="absolute right-4 top-3 text-xl">×</button><h2 className="text-xl font-bold">Sign in to your account</h2><p className="mt-2 text-sm text-slate-500">Access your saved properties and enquiries.</p><input type="email" placeholder="Email address" className="mt-5 w-full rounded border border-slate-200 p-3 text-sm text-ink"/><input type="password" placeholder="Password" className="mt-3 w-full rounded border border-slate-200 p-3 text-sm text-ink"/><Button className="mt-4 w-full">Sign In</Button></form></div>}
 </main>;
}
